### ISSUE TITLE
My personal opinion

### ISSUE THREAD

**Issue by janIpen** [Mouthless-Stoat/Xper#2]
This language takes too many features from Rust that just don't fit with this kind of language e.g. lifetimes.

**Comment by Mouthless-Stoat** [comment]
The only feature that was actually inspire by Rust is range and lifetime is a rip off of dreamberd

**Comment by janIpen** [comment]
> The only feature that was actually inspire by Rust is range and lifetime is a rip off of dreamberd

Ok then, I thought dreamberd's lifetime system was an antipattern for language creation

**Comment by Mouthless-Stoat** [comment]
Yes that the point it just a big meme that happen because I was bored. Not mean to be serious in any capacity, just stuff that I thought could be interesting to implement and mess around with
